config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :spaces do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]

  root to: 'pages#home'

  get "/dashboard", to: "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space
  validates :date, presence: true
  enum status: [ :pending, :approved, :declined ]
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  validates :address, presence: true
  validates :price, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :spaces
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!
  # Add exceptions to above line - Ie: ', only: :home'

  def index
  end

  def show
    @booking = current_user.bookings.find(params[:id])
  end

  def new
    @space = Space.find(params[:space_id])
    @booking = Booking.new
  end

  def create
    @space = Space.find(params[:space_id])
    @booking = current_user.bookings.new(booking_params)
    @booking.status = "pending"
    @booking.space = @space
    authorize @booking
    if @booking.save(booking_params)
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(booking_params)
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status: params[:status])
    redirect_to dashboard_path
  end

  def destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :space_id, :date, :status)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def index
    @user = current_user
    @spaces = @user.spaces
    @my_bookings = @user.bookings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  # Add exceptions to above line - Ie: ', only: :home'
  def home
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!

  # Add exceptions to above line - Ie: ', only: :home'

  def index
     @spaces = policy_scope(Space).order(created_at: :desc)
    if any_of_search_params_present?
      @spaces = filter_spaces
    else
      @spaces = Space.all
    end
  end

  def show
    @space = Space.find(params[:id])
    @booking = Booking.new
    authorize @space
    if current_user
      @userbookings = @space.bookings.select { |b| b.user_id == current_user.id }.sort_by { |booking| booking.date}
    else
      @userbookings = []
    end
  end

  def new
    @space = Space.new
    authorize @space
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    authorize @space
    if @space.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def edit
     @space = Space.find(params[:id])
     authorize @space
  end

  def update
    @space = Space.find(params[:id])
    @space.update(space_params)
    redirect_to space_path(@space)
     authorize @space
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy
    redirect_to dashboard_path
  end

  private

  def space_params
    params.require(:space).permit(:description, :name, :address, :capacity, :price, :photo, :user_id, :booking_id)
  end

  def any_of_search_params_present?
    params[:address].present? || params[:price].present? || params[:capacity].present?
  end

  def filter_spaces
    price = params[:price].present? ? params[:price] : Float::INFINITY
    capacity = params[:capacity].present? ? params[:capacity] : 100000
    Space.where("address ILIKE ?", "%#{params[:address]}%")
         .where("price <= ?", price)
         .where("capacity <= ?", capacity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class=" background-new-space-page">

  <h1 class="title-new-page">Edit your Spaces</h1>

  <div class="form-box">
      <%= simple_form_for(@space) do |f| %>
        <%= f.input :name, label: "Name: " %>
        <%= f.input :address, label: "Address:" %>
        <%= f.input :capacity, label: "Capacity:" %>
        <%= f.input :price, label: "Price:" %>
        <%= f.input :description, label: "Description" %>
        <%= f.input :photo, label: "Photo" %>
        <%= f.submit "Add Space", class: "btn btn-primary btn-new-space" %>
      <% end %>
  </div>

</div>

app/views/bookings/index.html.erb
<h1>Welcome to your places list <%= current_user.email %></h1>


<div class="row ">
    <% @spaces.each do |space| %>
      <div class="col-xs-12 col-md-10 col-lg-10">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.4)), url(<%= space.photo %>);">

          <div class="card-category">
            <%= space.name%>

            <%= link_to "Edit my space", edit_space_path(space), class: "btn btn-lg" %>

          </div>
          <%= link_to "view details >", space_path(space), class: "card-link" %>

        </div>
      </div>

      <ul>
        <%=  %>
      </ul>
    <% end %>
  </div>

app/views/dashboard/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-lg-4">
      <h1 class="header-top-margin">Dashboard <%= @user.email %></h1>
      <div class="dashboard-card">
        <div class="space-card-content">
          <% if @my_bookings.blank? %>
            <p>You still don't have any bookings.
            <%= link_to "Search for a nice place", spaces_path %></p>
          <% else %>
            <h3>Bookings I made:</h3>
            <% @my_bookings.each do |booking| %>
              <p><%= booking.space.name %> at <strong><%= booking.date %></strong></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div> <!-- Col -->

    <div class="col-12 col-lg-8">
      <% if @spaces.blank? %>
        <p></p>
      <% else %>
        <h1 class="header-top-margin">The list of your spaces</h1>
        <% @spaces.each do |space| %>
          <div class="row dashboard-card">
            <div class="col-12 col-lg-4">
              <div class="space-card-owner-image rounded" style="background-image: url(<%= cl_image_path space.photo %>);">
              </div>
            </div>
            <div class="col-12 col-lg-8">
              <div class="dashboard-content">
                <%= link_to space.name, space_path(space), class: "btn btn-primary" %>
                <%= link_to "Edit my space", edit_space_path(space.id), class: "btn btn-primary" %>
                <% if space.bookings.blank? %>
                  <h3 class="header-top-margin">No bookings yet</h3>
                <% else %>
                  <h3 class="header-top-margin">Bookings for this space:</h3>
                <% end %>
                <% space.bookings.each do |booking| %>
                  <div class="row dashboard-booking-margin">
                    <div class="col-12 col-md-6">
                      <strong><%= l(booking.date, format: :long) %></strong> by <%= booking.user.email %> -
                      <% if booking.pending? %>
                        <span class="text-danger">Pending: </span><i class="far fa-question-circle text-danger"></i>&nbsp;&nbsp;&nbsp;
                      <% elsif booking.approved? %>
                        <span class="text-success">Approved: </span><i class="far fa-check-circle text-success"></i>&nbsp;&nbsp;&nbsp;
                      <% elsif booking.declined? %>
                        <span class="text-primary">Declined:&nbsp;&nbsp;&nbsp;</span><i class="fas fa-ban text-primary"></i>&nbsp;&nbsp;&nbsp;
                      <% end %>
                    </div>
                    <div class="col-12 col-md-6">
                      <%= link_to "Approve", booking_path(booking, status: "approved"), class: "btn btn-sm btn-success", method: :patch %> -
                      <%= link_to "Decline", booking_path(booking, status: "declined"), class: "btn btn-sm btn-primary", method: :patch  %>
                    </div>
                    <hr>
                  </div>
                <% end %> <!-- each.do booking -->
              </div> <!-- Card content -->
            </div> <!-- Col -->
         </div> <!-- row -->
        <% end %> <!-- each do space -->
      <% end %> <!-- spaces blank -->
    </div> <!-- Col -->
  </div> <!-- row -->
</div> <!-- container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bars for events</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <div class="footer d-flex">
      <div class="footer-links d-flex">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Bars made with <i class="fas fa-heart"></i> in Barcelona
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://spmodels.net/malacca/wp-content/uploads/2016/01/Event-Management-service-AnnualDinner.jpg');">
  <div class="banner-content">
    <h1>Find the perfect location for your event</h1>
    <div class="form-inline justify-content-center">
      <%= form_tag(spaces_path, method: :get) do %>
        <%= text_field_tag :address, params[:address], placeholder: "type in a city", class: "form-control form-control-lg form-fields" %>
        <%= submit_tag 'Start', class: "btn btn-primary btn-lg form-fields" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon d-flex">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-blue.png", height: 50 %>
  <% end %>
  <h3 class="text-danger">AirB-n-Bar</h3>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right d-flex">

    <%= link_to "Show all Spaces", spaces_path, class: "navbar-wagon-item navbar-wagon-link d-none d-md-block" %>

    <!-- Links when logged in -->
    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item d-none d-md-block">
        <div class="dropdown">
          <%= image_tag "face-avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to new_space_path do %>
                <i class="fas fa-plus"></i>  <%= t(".new", default: "Add new Space") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fas fa-cog"></i>  <%= t(".dashboard", default: "My Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item d-md-none">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to spaces_path do %>
            <%= t(".spaces", default: "Show all Spaces") %>
          <% end %>
        </li>

        <!-- Links when logged in -->
        <% if user_signed_in? %>

          <li>
          <%= link_to new_space_path do %>
            <%= t(".new", default: "Add new Space") %>
          <% end %>
          </li>
          <li>
            <%= link_to bookings_path do %>
              <%= t(".bookings", default: "My Dashboard") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>

        <% else %>
         <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </ul>
    </div>
  </div>

</div>

app/views/spaces/edit.html.erb
<div class="background-edit-space-page">
  <div class="space-form-container">
    <div class="form-box">
      <h1 class="title-new-page">Edit Your Event Space</h1>
      <%= simple_form_for(@space) do |f| %>
        <%= f.input :name, label: "Name: " %>
        <%= f.input :address, label: "Address:" %>
        <%= f.input :capacity, label: "Capacity:" %>
        <%= f.input :price, label: "Price:" %>
        <%= f.input :description, label: "Description" %>
        <%= f.input :photo, label: "Photo" %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Edit Space", class: "btn btn-primary btn-lg btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/spaces/index.html.erb
<div class="container-fluid">
  <div class="row filter-bar">
    <div class="col-12">
      <div class="form-inline">
        <%= simple_form_for(spaces_path, method: :get) do %>
          <%= text_field_tag :address, params[:address], placeholder: "Choose a city", class: "form-control form-fields" %>
          <%= text_field_tag :price, params[:price], placeholder: "Max Price", class: "form-control form-fields" %>
          <%= text_field_tag :capacity, params[:capacity], placeholder: "Min Capacity", class: "form-control form-fields" %>
          <%= submit_tag 'Search', class: "btn btn-primary form-control form-fields" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 space-card-header">
      <h1>Choose venue for your next event</h1>
    </div>
  </div>
  <div class="row d-flex">
    <% @spaces.each do |space| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="space-card">
          <div class="space-card-image" style="background-image: url(<%= cl_image_path space.photo %>);">
          </div>
          <div class="space-card-content">
            <h4><%= space.name.upcase[0..30] %>&hellip;</h4>
            <h2><%= space.address[0..50] %>&hellip;</h2>
            <div class="space-card-price">&euro; <%= space.price.to_i %> per day &#8226; Free cancellation</div>
            <p><i class="far fa-envelope"></i> owner: <%= space.user.email %></p>
            <!-- <%= link_to "view details >" , space_path(space), class: "btn btn-info" %> -->
            <!-- # <%= link_to "Delete " , space_path(space), method: :delete %> -->
          </div>

          <%= link_to "view details >", space_path(space), class: "space-card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="background-new-space-page">
  <div class="space-form-container">
    <div class="form-box">
      <h1 class="title-new-page">Add a new Space</h1>
      <%= simple_form_for(@space) do |f| %>
        <%= f.input :name, label: "Name: " %>
        <%= f.input :address, label: "Address:" %>
        <%= f.input :capacity, label: "Capacity:" %>
        <%= f.input :price, label: "Price:" %>
        <%= f.input :description, label: "Description" %>
        <%= f.input :photo, label: "Photo" %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Add Space", class: "btn btn-primary btn-lg btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/spaces/show.html.erb
<div class="banner-space-img" style="background-image: url('<%= cl_image_path @space.photo %>');">
  <div class="banner-lower-left">
    <% if current_user %>
      <% if @space.user_id == current_user.id %>
        <%= link_to "Edit my space", edit_space_path, class: "btn btn-lg btn-primary" %>
      <% elsif @space.user_id != current_user.id %>
        <button type="button" class="btn btn-lg btn-danger" data-toggle="modal" data-target="#bookModal">Book This Place</button>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="background-space-info">
        <h1><%= @space.name %></h1>
        <p><%= @space.address %></p>
        <p><i class="fas fa-users"></i> <%= @space.capacity %> people</p>
        <h3><i class="fas fa-euro-sign"></i> <%= @space.price.to_i %> for 24 hours</h3>
        <p><%= @space.description %></p>
      </div>
    </div>
    <div class="col-12 col-md-6 text-center">
      <div class="background-space-info"> <!-- Bookings -->
        <% if @userbookings != [] %>
          <h2><i class="far fa-calendar"></i> Your bookings</h2>
          <% @userbookings.each do |b| %>
            <h3>
              <% if b.status == nil %>
                You have no bookings yet
              <% elsif b.approved? %>
                <span class="text-success">Approved </span><i class="far fa-check-circle text-success"></i> <%= b.date %>
              <% elsif b.pending? %>
              <span class="text-primary">Pending </span><i class="far fa-question-circle text-primary"></i> <%= b.date %>
              <% else %>
                <span class="text-danger">Declined </span><i class="fas fa-ban text-danger"></i> <%= b.date %>
              <% end %>
            </h3>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="bookModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Book</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for([@space, @booking]) do |b| %>
          <%= b.input :date, label: "Date: " %>
          <%= b.hidden_field :status %>
          <%= b.hidden_field :user_id %>
          <%= b.hidden_field :space_id %>
          <%= b.submit "Book", class: "btn btn-primary btn-lg btn-block" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>